import { DM_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";

const playfair_display = Playfair_Display({
  // variable: "--font-geist-sans",
  subsets: ["latin", "cyrillic"],
  weight: ['400', '500', '600', '700', '800', '900'],
});

const dn_sans = DM_Sans({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair_display.className} ${dn_sans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
